---
stages:
  - lint

golint:
  stage: lint
  tags: [cluster]
  before_script:
    - apk add go
    - go get -u golang.org/x/lint/golint
    - export PATH=$PATH:/root/go/bin/
  script:
    - golint *.go
  image: alpine

